[OF-1096] test: added tests for common Map
magnopus-opensource/connected-spaces-platform pull request #153
Opened 2023-09-06 09:00 UTC by MAG-AW

connected-spaces-platform Pull Request

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2023-09-06 09:55 UTC, MAG-MichaelK requested changes

2023-09-06 09:55 UTC, MAG-MichaelK commented on Tests/Map.cpp
> +};
We should try to adhere to the same testing style in all of our tests. Other csp::common tests create the test object locally. Relying on a class having the test object as a field changes the lifetime and behaviour of said test object.

2023-09-06 09:55 UTC, MAG-MichaelK commented on Tests/Map.cpp
> +#endif
As these are meant to be unit tests, we should be testing every public function of Map with various value types. This means constructors, operator overloads, copy assignment, etc. You can refer to the existing tests for Array, Optional, String, etc.

2023-09-06 11:10 UTC, MAG-MichaelK requested changes

2023-09-06 11:10 UTC, MAG-MichaelK commented on Tests/Map.cpp
> +	EXPECT_TRUE(MyMap.HasKey(3));
It's worth checking the values too.

2023-09-06 11:10 UTC, MAG-MichaelK commented on Tests/Map.cpp
> +#endif
I see that the copy constructor is being tested, but not the move constructor. Copy and move assignment are also missing, as are tests for Keys(), Values(), and Clear().

2023-09-06 11:10 UTC, MAG-MichaelK commented on Tests/Map.cpp
> +	EXPECT_TRUE(MyMap.HasKey(3));
It's worth checking if Size() returns what we expect here.

2023-09-06 11:56 UTC, MAG-MichaelK requested changes

2023-09-06 11:56 UTC, MAG-MichaelK commented on Tests/src/InternalTests/CommonTypeTests/Map.cpp
> +}
This should be split into 3 separate tests. We want to keep our unit tests as small as possible and only test a single unit at a time.

2023-09-06 13:12 UTC, MAG-MichaelK requested changes

2023-09-06 13:12 UTC, MAG-MichaelK commented on Tests/src/InternalTests/CommonTypeTests/Map.cpp
> +	EXPECT_FALSE(MyMap.Values()->Data() == nullptr);
`Keys()` and `Values()` returns a newly-allocated array, so we should store and delete it.

2023-09-07 08:25 UTC, MAG-MichaelK approved these changes

2023-09-07 08:55 UTC, MAG-SamBirley approved these changes

2023-09-07 08:56 UTC, merged