[NT-0] refac: ensure platform define always set
magnopus-opensource/connected-spaces-platform pull request #205
Opened 2023-10-03 14:12 UTC by MAG-MichaelK

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2023-10-06 10:48 UTC, MAG-AdamThorn submitted a review, later dismissed

2023-10-06 12:52 UTC, MAG-SamBirley approved these changes
This is neat! This will however break C++ clients (like our internal Unreal client) where they have these already defined. 

If you agree, please can we telegraph this as a breaking change?

cc @MAG-AdamThorn

2023-10-06 13:32 UTC, MAG-MichaelK commented
Ah I should have caught that. I'll add protection against that by using something like `ifndef CSP_WINDOWS def CSP_WINDOWS`

2023-10-06 14:31 UTC, MAG-SamBirley requested changes
Setting review state to `request changes` to avoid this getting accidentally merged.

2023-11-14 13:06 UTC, MAG-SamBirley approved these changes

2023-11-15 16:11 UTC, merged