[OF-1148] fix: release notes on web
magnopus-opensource/connected-spaces-platform pull request #259
Opened 2023-11-16 11:15 UTC by MAG-AW

connected-spaces-platform Pull Request

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2023-11-16 11:18 UTC, MAG-MichaelK requested changes

2023-11-16 11:18 UTC, MAG-MichaelK commented on teamcity/BuildNPMWebPackage.py
> +        with open(f"{output_path}/README.md.meta", "w") as f:
Meta files are Unity-specific and are not needed for the web package.

2023-11-16 11:21 UTC, MAG-MichaelK approved these changes

2023-11-16 12:33 UTC, MAG-AdamThorn requested changes

2023-11-16 12:33 UTC, MAG-AdamThorn commented on teamcity/BuildNPMWebPackage.py
> +    # Copy readme and create meta file
Remove 'and create meta file' from the comment

2023-11-16 12:45 UTC, MAG-MichaelK approved these changes

2023-11-17 09:39 UTC, Mag-JB submitted a review, later dismissed

2023-11-17 12:47 UTC, MAG-MichaelK requested changes

2023-11-17 12:47 UTC, MAG-MichaelK commented on teamcity/GenerateReadme_NEW.py
We should ensure that all commits adhere to our standard. All developers should be using the pre-commit githooks that we include in our repo, unless they explicitly disable them or use the github UI to author a change.

2023-11-17 12:47 UTC, MAG-MichaelK commented on teamcity/GenerateReadme_NEW.py
> +                continue
Can we get a blank line after `continue`, please?

2023-11-17 12:47 UTC, MAG-MichaelK commented on teamcity/GenerateReadme_NEW.py
> +            is_breaking_change = False
I don't think we should assume that non-adhering commits are never breaking changes

2023-11-17 12:47 UTC, MAG-MichaelK commented on teamcity/templates/readme/readme.md.jinja2
> +| {{ commit.hexsha | truncate(7, true, '') }} | {{ commit.author }} | {{ commit.message | trim | replace('\r', '') | replace('\n\n', '<br>') | replace('\n', '<br>') | replace('*', '&bull;')}}|
Why was an explicit replace for `\r` added here? Commit messages should never contain carriage returns by the standard of git.

Also, a space is missing before the last `}}`

2023-11-17 13:26 UTC, MAG-MichaelK approved these changes

2023-11-17 13:32 UTC, MAG-SamBirley approved these changes

2023-11-22 09:09 UTC, merged