[NT-0] fix: space deletion test time workaround
magnopus-opensource/connected-spaces-platform pull request #264
Opened 2023-11-17 16:45 UTC by MAG-SamBirley

A service-side issue with our new approach to handling space deletion has been found  which has drastically increased the time of our functional tests.

As a short-term workaround to keep our functional test time manageable,
 we are restoring the previous approach.

As soon as we've resolved the service-side issue, we'll be restoring the
 new implementation, and this workaround can be removed.

2023-11-17 16:58 UTC, MAG-SamBirley commented on Library/src/Systems/Spaces/SpaceSystem.cpp
> +					static const bool SPACE_DELETION_WORKAROUND = true;
Great point, fixing!

2023-11-17 16:59 UTC, MAG-SamBirley commented on Library/src/Systems/Spaces/SpaceSystem.cpp
> +					static const bool SPACE_DELETION_WORKAROUND = true;
Fixed in latest

2023-11-20 10:23 UTC, MAG-MichaelK requested changes

2023-11-20 10:23 UTC, MAG-MichaelK commented on Library/src/Systems/Spaces/SpaceSystem.cpp
> +					const bool SPACE_DELETION_WORKAROUND = CSPFoundation::GetTenant() == "OKO_TESTS";
`UPPER_SNAKE_CASE` should only be used for values that can be evaluated at compile time.

2023-11-20 10:23 UTC, MAG-MichaelK commented on Library/src/Systems/Spaces/SpaceSystem.cpp
> +					if (SPACE_DELETION_WORKAROUND)
Can we get a new line before this if block, please?

2023-11-20 13:41 UTC, MAG-SamBirley commented
This change does not seem to be having the expected result, test times are unaffected by the workaround. Running one final test and if the result is the same, I'll be closing this PR.

2023-11-21 12:23 UTC, MAG-SamBirley commented
The result was the same with the final test. Closing as per my previous comment.

2023-11-21 12:30 UTC, closed without merging