[OB-953] fix: FileAssetDataSource bad path
magnopus-opensource/connected-spaces-platform pull request #314
Opened 2024-01-25 10:04 UTC by MAG-AW

* Fixed a crash when a bad path was supplied for a file upload
* Added a test for bad paths in uploads

connected-spaces-platform Pull Request

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2024-01-25 10:17 UTC, MAG-AdamThorn approved these changes

2024-01-25 12:08 UTC, MAG-SamBirley requested changes

2024-01-25 12:08 UTC, MAG-SamBirley commented on Library/src/Web/POCOWebClient/POCOWebClient.cpp
> +		CSP_LOG_WARN_MSG("File not found.");
Could we also print the file path to the log here? That'd be really useful for developers diagnosing problems in their code

2024-01-25 16:34 UTC, MAG-SamBirley approved these changes

2024-01-26 11:25 UTC, MAG-AdamThorn approved these changes

2024-01-26 16:47 UTC, merged