[OF-1233] feat: add OrganizationId to Space
magnopus-opensource/connected-spaces-platform pull request #418
Opened 2024-05-22 10:53 UTC by MAG-AW

connected-spaces-platform Pull Request

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2024-05-22 10:59 UTC, MAG-MichaelK requested changes

2024-05-22 10:59 UTC, MAG-MichaelK commented on Tests/src/PublicAPITests/OrganizationSystemTests.cpp
> +	EXPECT_EQ(Space.OrganizationId, "661ea67b07a518c46909dc97");
Hard-coded IDs are never good. Can we store this with the login details instead?

2024-05-22 10:59 UTC, MAG-MichaelK commented on Tests/src/PublicAPITests/OrganizationSystemTests.cpp
> +	EXPECT_TRUE(HasOrgAccountDetails);
Really nit-picky, but can we get a new line before this, please?

2024-05-22 11:01 UTC, MAG-MichaelK commented on Tests/src/PublicAPITests/OrganizationSystemTests.cpp
> +	EXPECT_EQ(Space.OrganizationId, "661ea67b07a518c46909dc97");
Better yet, can we retrieve this from CHS at runtime?

2024-05-22 11:32 UTC, MAG-AdamThorn requested changes

2024-05-22 11:32 UTC, MAG-AdamThorn commented on Tests/src/PublicAPITests/OrganizationSystemTests.cpp
> +	// Log in - user needs to be an admin member of the organization
They don't need to be an admin. Can you move the comment after the '-' please?

2024-05-24 08:33 UTC, MAG-AdamThorn approved these changes

2024-05-24 08:33 UTC, merged