[OF-1335] feat: Added HotspotSpaceComponent
magnopus-opensource/connected-spaces-platform pull request #435
Opened 2024-07-04 10:12 UTC by MAG-AW

* Added the new Component
* Added script bindings
* Added tests

*Removed duplicated TextSpaceComponent script bindings

2024-07-04 12:58 UTC, MAG-AdamThorn requested changes

2024-07-04 12:58 UTC, MAG-AdamThorn commented on Library/include/CSP/Multiplayer/Components/HotspotSpaceComponent.h
> +    HotspotType GetHotspotType() const;
Missing documentation for for get/set hotspot type.

2024-07-04 12:58 UTC, MAG-AdamThorn commented on Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp
> +	// Create text component
The comment should say 'hotspot'

2024-07-04 13:46 UTC, MAG-AdamThorn commented on Library/include/CSP/Multiplayer/Components/HotspotSpaceComponent.h
> +	DEFAULT = 0,
That was likely missed when we moved away from the idea of using the POI System. I think you can remove it unless you are aware of any reason to keep it.

2024-07-05 15:33 UTC, MAG-AdamThorn approved these changes

2024-07-05 15:35 UTC, MAG-AdamThorn commented on Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp
> +	EXPECT_EQ(HotspotComponent->GetHotspotType(), HotspotType::DEFAULT);
Yes... yes I am!
Thanks

2024-07-05 15:46 UTC, MAG-mv commented on Library/src/Multiplayer/Components/HotspotSpaceComponent.cpp
> +const csp::common::String& HotspotSpaceComponent::GetUniqueComponentId()
Why is UniqueComponentId a property of the class? Is it worth removing this and making the function const?

2024-07-08 14:02 UTC, MAG-mv approved these changes

2024-07-08 15:02 UTC, MAG-AdamThorn approved these changes

2024-07-08 15:02 UTC, merged