NT-O_Add_repo_name_check_to_GitHub_Actions
magnopus-opensource/connected-spaces-platform pull request #477
Opened 2024-09-10 11:32 UTC by MAG-AdamThorn

To ensure that our GitHub Actions do not run on forks of the Connected Spaces Platform repo, checks have been added to ensure the repo name is correct.

**For the reviewer**

* [ ] If required, are the changes covered by appropriate tests?
* [ ] Are any public-facing API changes well documented?
* [ ] Is the code easily readable and extensible and/or follow existing conventions?

2024-09-20 10:52 UTC, MAG-SamBirley requested changes

2024-09-20 10:52 UTC, MAG-SamBirley commented on .github/workflows/staging-newBranch-restrict.yml
> +        if: contains(github.base_ref, 'staging/') && github.head_ref == 'develop'
Think this should be `!= Develop`

2024-09-24 08:41 UTC, MAG-AdamThorn commented on .github/workflows/staging-newBranch-restrict.yml
> +        if: contains(github.base_ref, 'staging/') && github.head_ref == 'develop'
Agreed, updated

2024-09-24 14:55 UTC, MAG-mv approved these changes

2024-09-24 15:08 UTC, MAG-SamBirley approved these changes

2024-09-24 15:48 UTC, merged