[OF-1419] feat: hotspot names support the space character
magnopus-opensource/connected-spaces-platform pull request #497
Opened 2024-09-26 13:38 UTC by MAG-SamBirley

CSP client applications can now reason about sequence keys that include characters usually reserved in URIs, such as spaces.

As part of this work, we have introduced a new set of encoding source files for future encode/decode behaviour.

During development, we discovered that there are some service endpoints currently expecting the provided keys to be _doubly_ encoded. The current approach takes this into account and double-encodes where necessary from a services point of view.

2024-09-26 13:49 UTC, MAG-SamBirley commented
WASM check is failing as this change depends on Poco URL formatting (we strip Poco out of WASM builds).

2024-09-26 14:30 UTC, MAG-SamBirley commented
Poco dependency for this change has now been stripped out. Instead of using Poco URI encoding, we use simple hand-rolled version instead.

2024-09-26 15:45 UTC, MAG-mv approved these changes

2024-09-26 16:26 UTC, MAG-mv submitted a review, later dismissed

2024-09-26 17:01 UTC, MAG-AdamThorn requested changes

2024-09-26 17:01 UTC, MAG-AdamThorn commented on Tests/src/InternalTests/EncodeTests.cpp
> +CSP_INTERNAL_TEST(CSPEngine, EncodeTests, EncodeURI)
As we are using double encoding for the sequence keys I think our tests should cover that.

2024-09-26 17:08 UTC, MAG-AdamThorn approved these changes

2024-09-26 17:20 UTC, MAG-mv approved these changes

2024-09-27 11:17 UTC, MAG-mv approved these changes

2024-09-27 14:35 UTC, MAG-AdamThorn approved these changes

2024-09-27 14:35 UTC, merged